#!/bin/bash
set -e

username=$1

if [ -z "$username" ]; then
  printf "Import GPG keys published by a GitHub user\n"
  printf "Usage: gh gpg-import github_username\n"
  exit 1
fi

echo "Importing published GPG keys for GitHub user ${username}"

keyBlob=$(gh api "users/${username}/gpg_keys")
keyCount=$(echo "$keyBlob" | jq -r ". | length")


if [ "$keyCount" == 0 ]
then
  echo "No keys found"
  exit 0
fi

for (( c=0; c<=keyCount; c++ ))
do
  rawKey=$(echo "$keyBlob" | jq -r ".[$c].raw_key")

  if [ "$rawKey" != "null" ]; then
    echo "$rawKey" | gpg --import
  fi
done

printf "\n\nKeys have been imported.\n"
printf "If you trust this user, consider signing their key using 'gpg --ask-cert-level --sign-key \$EMAIL'\n"
